---
version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/traefik.toml:/traefik.toml"
      - "./traefik/conf.d:/conf.d"
      - type: bind
        source: "./traefik/acme.json"
        target: "/acme.json"

  proxy:
    build:
      context: apache
    depends_on:
      - traefik
    volumes:
      - type: bind
        source: "${PWD}/apache/passwords"
        target: "/etc/apache2/passwords"
      - type: bind
        source: "${PWD}/apache/reverseproxy.conf"
        target: "/etc/apache2/sites-enabled/reverseproxy.conf"
    networks:
      jupyterhub:
          ipv4_address: 172.21.11.2
      traefik:
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.certresolver=le"
      - "traefik.http.routers.proxy.entrypoints=https"
      - "traefik.http.routers.proxy.service=proxy"
      - "traefik.http.services.proxy.loadbalancer.server.port=80"
      - "traefik.docker.network=reverseproxy_traefik"

  hub1:
    build:
      context: jupyterhub
    volumes:
      - "${PWD}/jupyterhub/jupyterhub1_config.py:/srv/jupyterhub/jupyterhub_config.py"
    expose:
      - 8000
    networks:
      jupyterhub:
        ipv4_address: 172.21.11.3

  hub2:
    build:
      context: jupyterhub
    volumes:
      - "${PWD}/jupyterhub/jupyterhub2_config.py:/srv/jupyterhub/jupyterhub_config.py"
    expose:
      - 8000
    networks:
      jupyterhub:
        ipv4_address: 172.21.11.4

  ep1:
    image: etherpad/etherpad
    environment:
      - TRUST_PROXY=true
      - MINIFY=false
    volumes:
      - "${PWD}/etherpad/settings.json:/opt/etherpad-lite/settings.json"
    expose:
      - 9001
    networks:
      jupyterhub:
        ipv4_address: 172.21.11.5

  ep2:
    image: etherpad/etherpad
    environment:
      - TRUST_PROXY=true
      - MINIFY=false
    volumes:
      - "${PWD}/etherpad/settings.json:/opt/etherpad-lite/settings.json"
    expose:
      - 9001
    networks:
      jupyterhub:
        ipv4_address: 172.21.11.6

networks:
  traefik:
  jupyterhub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.11.0/24
          gateway: 172.21.11.1
